import { reflective as m } from './model';
export declare function createEquals<M extends m.ModelElement>(specificEquals: (m: M) => boolean): (m: m.ModelElement) => any;
export declare function createTypeEquals<M extends m.Type>(specificEquals: (m: M) => boolean): (m: m.ModelElement) => any;
export declare function createExpressionEquals<M extends m.Expression<any>>(specificEquals: (m: M) => boolean): any;
export declare const containerEquals: (m: m.ModelElement) => any;
export declare const containedEquals: (m: m.ModelElement) => any;
export declare const protoClassEquals: (m: m.ModelElement) => any;
export declare const constructableTypeEquals: (m: m.ModelElement) => any;
export declare const typeParameterEquals: (m: m.ModelElement) => any;
export declare const compositeTypeEquals: (m: m.ModelElement) => any;
export declare const indexEquals: (m: m.ModelElement) => any;
export declare const memberEquals: (m: m.ModelElement) => any;
export declare const enumMemberEquals: (m: m.ModelElement) => any;
export declare const primitiveTypeEquals: (m: m.ModelElement) => any;
export declare const decoratorTypeEquals: (m: m.ModelElement) => boolean;
export declare const functionTypeEquals: (m: m.ModelElement) => any;
export declare const parameterEquals: (m: m.ModelElement) => any;
export declare const tupleTypeEquals: (m: m.ModelElement) => any;
export declare const unionOrIntersectionTypeEquals: (m: m.ModelElement) => any;
export declare const typeQueryEquals: (m: m.ModelElement) => any;
export declare const valueExpressionEquals: any;
export declare const primitiveExpressionEquals: any;
export declare const arrayExpressionEquals: any;
export declare const objectExpressionEquals: any;
export declare const classExpressionEquals: any;
export declare const classReferenceExpressionEquals: any;
export declare const functionExpressionEquals: any;
export declare const functionCallExpressionEquals: any;
export declare const newExpressionEquals: any;
export declare const propertyAccessExpressionEquals: any;
export declare const enumExpressionEquals: any;
export declare const decoratorEquals: (m: m.ModelElement) => any;
